#!/usr/bin/env bash

DAY="$1"
YEAR=2021

DAY_DIR="$PWD/$DAY"
DAY_INPUT="$DAY_DIR/input"
DAY_MAIN="$DAY_DIR/main.ts"
DAY_PART_1="$DAY_DIR/part_1.ts"
DAY_PART_2="$DAY_DIR/part_2.ts"

DENO_CMD="deno run --watch --allow-read $DAY_MAIN"

if [ -z "$DAY" ]; then
  echo "No Argument found! Please use like:"
  echo "    init_day N (1-31)"
  exit 1
fi

if [ ! -d "$DAY_DIR" ]; then
  cp -r .template "$DAY_DIR"
fi

curl --silent --location \
  --output "$DAY_INPUT" \
  --cookie session=$(cat session.cookie) \
  https://adventofcode.com/"$YEAR"/day/"$DAY"/input

i3-msg --quiet "exec WINIT_X11_SCALE_FACTOR=1 alacritty --working-directory $DAY_DIR --command $DENO_CMD"
vim "$DAY_PART_1"
